
services:
    zeldoh.ground_extension:
        class: Zeldoh\AppBundle\Twig\GroundExtension
        arguments:
            - @router
        tags:
            - { name: twig.extension }
    zeldoh.map.loader:
        class: Zeldoh\AppBundle\Service\MapLoader
    zeldoh.monster.manager:
        class: Zeldoh\AppBundle\Service\MonsterManager
    zeldoh.registrationListener:
        class: Zeldoh\AppBundle\EventListener\RegistrationListener
        arguments: 
            - "@router"
        tags: 
            - { name: kernel.event_subscriber }
#        arguments: [@service_id, "plain_value", %parameter%]
#        calls:
#            - [setService, [@service_id]]
#        tags:
#            - { name: twig.extension }
#            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }