zeldoh_app:
    resource: "@ZeldohAppBundle/Controller/"
    type:     annotation
    prefix:   /

zeldoh_api:
    resource: "@ZeldohApiBundle/Controller/"
    type:     annotation
    prefix:   /api

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"